### ISSUE TITLE
Compiler warning in positioning.h

### ISSUE THREAD

**Issue by wolfv** [NativeInstruments/ni-media#15]
`/home/wolfv/Programs/ni-media/audiostream/src/ni/media/iostreams/positioning.h:35:14: warning: enumeration value '_S_ios_seekdir_end' not handled in switch [-Wswitch]`

As it's the only warning and seems easy to solve, would be nice! :)

**Comment by Foaly** [comment]
Hmm I can't reproduce the warning using Clang Apple LLVM version 9.0.0
What compiler version + OS are you using?

**Comment by wolfv** [comment]
`clang++ -v` gives `clang version 5.0.1 (tags/RELEASE_501/final)`
on Fedora 27

**Comment by Foaly** [comment]
From a quick google around this seems to be a [compiler bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67996) (more specifically in libstdc++). So a workaround would be to get rid of the switch, but I would say the proper solution is a compiler update :)

**Comment by marcrambo** [comment]
we could also simply add a `default` case which asserts and returns -1 (i.e.) eof.

**Comment by marcrambo** [comment]
Could not reproduce this warning but PR #19 should fix it. Also we added some checks on the CI in PR #20 so the code remains warning free. Thanks for reporting.
