### ISSUE TITLE
how to get the waveform data of wav file？

### ISSUE THREAD

**Issue by ucasiggcas** [NativeInstruments/ni-media#25]
Dear，
Could help me get the waveform data of wav file？
THX

**Comment by marcrambo** [comment]
Hey! 

The Wav format is supported on all platforms. What exactly is the problem you are facing? 
As a starting point you could try the code below which will read in an entire wav file into an interleaved vector. 
```
    auto stream = audio::ifstream("hello.wav");
    auto samples = std::vector<float>(stream.info().num_samples());
    stream >> samples;
```

**Comment by ucasiggcas** [comment]
#include <boost/range/difference_type.hpp>
#include <boost/range/has_range_iterator.hpp>
#include <boost/range/value_type.hpp>
Sorry，I can‘t find these three headers，could U help me？

**Comment by marcrambo** [comment]
It seems like you are missing the boost libraries. Boost is a required dependency. Cmake should have triggered an error during configure time about the missing library. Are you using cmake? 

You can use Visual Studio 2015 and above.

**Comment by ucasiggcas** [comment]
But U haven't proposed the files !!!
Couldn't find !
Help !
Thx

**Comment by FalconPDX** [comment]
Hiya.

You need to install the boost libraries and then include them in your VS solution.  Here is a guide for windows: https://www.boost.org/doc/libs/1_68_0/more/getting_started/windows.html

**Comment by FalconPDX** [comment]
Hi @ucasiggcas did you get it to work? :)
