### ISSUE TITLE
Old gcc does not support c++14!

### ISSUE THREAD

**Issue by lqniunjunlper** [NativeInstruments/ni-media#39]
How to adapt the code to c++11? thanks for advice.

**Comment by marcrambo** [comment]
Ni-media was originally developed with c++11 and most of the code does not need c++14. To support c++11 you would have to adapt some of the code in the pcm subfolder, mostly adding replacements of c++14 only stl meta template additions like `std::index_sequence` (see e.g. https://github.com/NativeInstruments/ni-media/blob/master/pcm/inc/ni/media/pcm/detail/tuple_to_array.h) ...
