### ISSUE TITLE
boost ERROR？

### ISSUE THREAD

**Issue by lqniunjunlper** [NativeInstruments/ni-media#40]
boost-1.69/boost/integer_traits.hpp:83:46: error: 'CHAR_MIN' was not declared in this scope
boost-1.69/boost/integer_traits.hpp:83:46: note: suggested alternative: '_SC_CHAR_MIN'

**Comment by marcrambo** [comment]
Which compiler are you using?

**Comment by lqniunjunlper** [comment]
gcc7 + boost-1.69

**Comment by lqniunjunlper** [comment]
It's so strange, actually CHAR_MIN, CHAR_MAX, SCHAR_MIN, SCHAR_MAX, ... has defined in <limits>. But i got erros like this:

ivectorstream.cpp:25:
container_source.h:25
device/container.h:25
iostreams/positioning.h:30
/boost-1.69/boost/iostreams/positioning.hpp:20:0,
 /boost-1.69/boost/integer_traits.hpp:83:46: error: 'CHAR_MIN' was not declared in this scope
 /boost-1.69/boost/integer_traits.hpp:83:46: note: suggested alternative: '_SC_CHAR_MIN'
 /boost-1.69/boost/integer_traits.hpp:83:56: error: 'CHAR_MAX' was not declared in this scope
 /boost-1.69/boost/integer_traits.hpp:83:56: note: suggested alternative: '_SC_CHAR_MAX'
 /boost-1.69/boost/integer_traits.hpp:83:64: error: template argument 2 is invalid
 /boost-1.69/boost/integer_traits.hpp:83:64: error: template argument 3 is invalid
 /boost-1.69/boost/integer_traits.hpp:89:53: error: 'SCHAR_MIN' was not declared in this scope
 /boost-1.69/boost/integer_traits.hpp:89:53: note: suggested alternative: '_SC_CHAR_MIN'
 /boost-1.69/boost/integer_traits.hpp:89:64: error: 'SCHAR_MAX' was not declared in this scope
 /boost-1.69/boost/integer_traits.hpp:89:64: note: suggested alternative: '_SC_CHAR_MAX'
 /boost-1.69/boost/integer_traits.hpp:89:73: error: template argument 2 is invalid
 /boost-1.69/boost/integer_traits.hpp:89:73: error: template argument 3 is invalid
 /boost-1.69/boost/integer_traits.hpp:95:58: error: 'UCHAR_MAX' was not declared in this scope
 /boost-1.69/boost/integer_traits.hpp:95:58: note: suggested alternative: '_SC_UCHAR_MAX'
 /boost-1.69/boost/integer_traits.hpp:95:67: error: template argument 3 is invalid
In file included from  /boost-1.69/boost/iostreams/positioning.hpp:20:0,

**Comment by marcrambo** [comment]
Gcc7 with boost 1-69 should work, although not explictety tested due to limited resources. We use a much lower gcc5 / boost 1.64 on our linux buildersver (see https://github.com/NativeInstruments/ni-media/blob/master/.travis.yml. ) so I'd expect your combination to work.  Maybe something went wrong when building boost?

**Comment by lqniunjunlper** [comment]
@marcrambo Problem solved. The limits.h in pcm folder has conflicts with default limits.h....
