### ISSUE TITLE
Linux does not support mp4 or m4a?

### ISSUE THREAD

**Issue by lqniunjunlper** [NativeInstruments/ni-media#41]
Only wav?

**Comment by lqniunjunlper** [comment]
Makefile:

`if ( APPLE OR WIN32 )
  option( NIMEDIA_ENABLE_MP3_DECODING  "Enable ni-media mp3 decoding" ON )
  option( NIMEDIA_ENABLE_MP4_DECODING  "Enable ni-media mp4 decoding" ON )
else()
  option( NIMEDIA_ENABLE_MP3_DECODING  "Enable ni-media mp3 decoding" OFF )
  option( NIMEDIA_ENABLE_MP4_DECODING  "Enable ni-media mp4 decoding" OFF )
endif()`

In os_source.h, there is no os_source definition for Linux?

`#pragma once

#include <ni/media/audio/source_impl.h>

#include <boost/predef.h>

#if BOOST_OS_MACOS || BOOST_OS_IOS
#include <ni/media/audio/os/mac/core_audio_source.h>
template <class Source>
using os_source = source_impl<core_audio_source<Source>>;
#elif BOOST_OS_WINDOWS
#include <ni/media/audio/os/win/media_foundation_source.h>
template <class Source>
using os_source = source_impl<media_foundation_source<Source>>;
#endif`

``

**Comment by marcrambo** [comment]
Mp3 and Mp4 are currently not supported on Linux. On linux only wav, aiff, ogg and flac extensions are supported see https://github.com/NativeInstruments/ni-media/blob/master/audiostream/doc/ifstream.md.

The audio:.ifstream constructor will throw a runtime error when passing an unsupported file path, which is expected behavior.  Client code should be using a try / catch block around the constructor and decide what to do in this case.

**Comment by lqniunjunlper** [comment]
Thanks@marcrambo 
Why Linux can not support mp4? Is there any plan for supporting mp4 on Linux?
Another question is how can we get meatadata of music, like sample-rate, bit-rate, artist,...

**Comment by lqniunjunlper** [comment]
How to generate a new music audio from scratch, in which there is track name, artist, etc,...
More importantly it can be played in musicpalyer.

**Comment by FalconPDX** [comment]
@lqniunjunlper 
ni-media does not generate audio, but simply streams it.  If you're looking for metadata support, you should check out [TagLib](https://taglib.org), which you can use alongside ni-media.

**Comment by FalconPDX** [comment]
Regarding your other comment about mp4 support, there was an initiative to integrate [GStreamer](https://gstreamer.freedesktop.org) into ni-media, which you can take a look at here:
https://github.com/NativeInstruments/ni-media/pull/11

**Comment by lqniunjunlper** [comment]
@FalconPDX Thanks
